export const tlist = [
  {
    num: 1,
    areaCode: '130100',
    area: '石家庄市',
    normal: 5,
    closed: 0,
    stoped: 0,
    merger: 0,
    switched: 0,
    countAll: 5,
    assess: 5,
    notAssess: 0,
    assessRate: '100.00%',
    policy: 5,
    notPolicy: 0,
    policyRate: '100.00%',
    riskCount: 5,
    notRiskCount: 0,
    riskRate: '100.00%'
  },
  {
    num: 2,
    areaCode: '130200',
    area: '唐山市',
    normal: 32,
    closed: 0,
    stoped: 0,
    merger: 0,
    switched: 0,
    countAll: 32,
    assess: 32,
    notAssess: 0,
    assessRate: '100.00%',
    policy: 27,
    notPolicy: 5,
    policyRate: '84.38%',
    riskCount: 27,
    notRiskCount: 0,
    riskRate: '100.00%'
  },
  {
    num: 3,
    areaCode: '130300',
    area: '秦皇岛市',
    normal: 10,
    closed: 0,
    stoped: 0,
    merger: 0,
    switched: 0,
    countAll: 10,
    assess: 10,
    notAssess: 0,
    assessRate: '100.00%',
    policy: 0,
    notPolicy: 10,
    policyRate: '0.00%',
    riskCount: null,
    notRiskCount: null,
    riskRate: null
  },
  {
    num: 4,
    areaCode: '130400',
    area: '邯郸市',
    normal: 2,
    closed: 0,
    stoped: 0,
    merger: 0,
    switched: 0,
    countAll: 2,
    assess: 2,
    notAssess: 0,
    assessRate: '100.00%',
    policy: 0,
    notPolicy: 2,
    policyRate: '0.00%',
    riskCount: null,
    notRiskCount: null,
    riskRate: null
  },
  {
    num: 5,
    areaCode: '130500',
    area: '邢台市',
    normal: 5,
    closed: 0,
    stoped: 0,
    merger: 0,
    switched: 0,
    countAll: 5,
    assess: 5,
    notAssess: 0,
    assessRate: '100.00%',
    policy: 3,
    notPolicy: 2,
    policyRate: '60.00%',
    riskCount: 3,
    notRiskCount: 0,
    riskRate: '100.00%'
  },
  {
    num: 6,
    areaCode: '130600',
    area: '保定市',
    normal: 2,
    closed: 0,
    stoped: 0,
    merger: 0,
    switched: 0,
    countAll: 2,
    assess: 2,
    notAssess: 0,
    assessRate: '100.00%',
    policy: 0,
    notPolicy: 2,
    policyRate: '0.00%',
    riskCount: null,
    notRiskCount: null,
    riskRate: null
  },
  {
    num: 7,
    areaCode: '130700',
    area: '张家口市',
    normal: 2,
    closed: 0,
    stoped: 0,
    merger: 0,
    switched: 0,
    countAll: 2,
    assess: 2,
    notAssess: 0,
    assessRate: '100.00%',
    policy: 0,
    notPolicy: 2,
    policyRate: '0.00%',
    riskCount: null,
    notRiskCount: null,
    riskRate: null
  },
  {
    num: 8,
    areaCode: '130800',
    area: '承德市',
    normal: 9,
    closed: 1,
    stoped: 0,
    merger: 0,
    switched: 0,
    countAll: 10,
    assess: 7,
    notAssess: 3,
    assessRate: '77.78%',
    policy: 0,
    notPolicy: 10,
    policyRate: '0.00%',
    riskCount: null,
    notRiskCount: null,
    riskRate: null
  },
  {
    num: 9,
    areaCode: null,
    area: '合计',
    normal: 67,
    closed: 1,
    stoped: 0,
    merger: 0,
    switched: 0,
    countAll: 68,
    assess: 65,
    notAssess: 3,
    assessRate: '97.01%',
    policy: 35,
    notPolicy: 33,
    policyRate: '52.24%',
    riskCount: 35,
    notRiskCount: 0,
    riskRate: '100.00%'
  },
  {
    num: 2,
    areaCode: '130200',
    area: '唐山市',
    normal: 32,
    closed: 0,
    stoped: 0,
    merger: 0,
    switched: 0,
    countAll: 32,
    assess: 32,
    notAssess: 0,
    assessRate: '100.00%',
    policy: 27,
    notPolicy: 5,
    policyRate: '84.38%',
    riskCount: 27,
    notRiskCount: 0,
    riskRate: '100.00%'
  },
  {
    num: 2,
    areaCode: '130200',
    area: '唐山市',
    normal: 32,
    closed: 0,
    stoped: 0,
    merger: 0,
    switched: 0,
    countAll: 32,
    assess: 32,
    notAssess: 0,
    assessRate: '100.00%',
    policy: 27,
    notPolicy: 5,
    policyRate: '84.38%',
    riskCount: 27,
    notRiskCount: 0,
    riskRate: '100.00%'
  },
  {
    num: 2,
    areaCode: '130200',
    area: '唐山市',
    normal: 32,
    closed: 0,
    stoped: 0,
    merger: 0,
    switched: 0,
    countAll: 32,
    assess: 32,
    notAssess: 0,
    assessRate: '100.00%',
    policy: 27,
    notPolicy: 5,
    policyRate: '84.38%',
    riskCount: 27,
    notRiskCount: 0,
    riskRate: '100.00%'
  },
  {
    num: 2,
    areaCode: '130200',
    area: '唐山市',
    normal: 32,
    closed: 0,
    stoped: 0,
    merger: 0,
    switched: 0,
    countAll: 32,
    assess: 32,
    notAssess: 0,
    assessRate: '100.00%',
    policy: 27,
    notPolicy: 5,
    policyRate: '84.38%',
    riskCount: 27,
    notRiskCount: 0,
    riskRate: '100.00%'
  },
  {
    num: 2,
    areaCode: '130200',
    area: '唐山市',
    normal: 32,
    closed: 0,
    stoped: 0,
    merger: 0,
    switched: 0,
    countAll: 32,
    assess: 32,
    notAssess: 0,
    assessRate: '100.00%',
    policy: 27,
    notPolicy: 5,
    policyRate: '84.38%',
    riskCount: 27,
    notRiskCount: 0,
    riskRate: '100.00%'
  },
  {
    num: 2,
    areaCode: '130200',
    area: '唐山市',
    normal: 32,
    closed: 0,
    stoped: 0,
    merger: 0,
    switched: 0,
    countAll: 32,
    assess: 32,
    notAssess: 0,
    assessRate: '100.00%',
    policy: 27,
    notPolicy: 5,
    policyRate: '84.38%',
    riskCount: 27,
    notRiskCount: 0,
    riskRate: '100.00%'
  },
  {
    num: 2,
    areaCode: '130200',
    area: '唐山市',
    normal: 32,
    closed: 0,
    stoped: 0,
    merger: 0,
    switched: 0,
    countAll: 32,
    assess: 32,
    notAssess: 0,
    assessRate: '100.00%',
    policy: 27,
    notPolicy: 5,
    policyRate: '84.38%',
    riskCount: 27,
    notRiskCount: 0,
    riskRate: '100.00%'
  },
  {
    num: 2,
    areaCode: '130200',
    area: '唐山市',
    normal: 32,
    closed: 0,
    stoped: 0,
    merger: 0,
    switched: 0,
    countAll: 32,
    assess: 32,
    notAssess: 0,
    assessRate: '100.00%',
    policy: 27,
    notPolicy: 5,
    policyRate: '84.38%',
    riskCount: 27,
    notRiskCount: 0,
    riskRate: '100.00%'
  },
  {
    num: 2,
    areaCode: '130200',
    area: '唐山市',
    normal: 32,
    closed: 0,
    stoped: 0,
    merger: 0,
    switched: 0,
    countAll: 32,
    assess: 32,
    notAssess: 0,
    assessRate: '100.00%',
    policy: 27,
    notPolicy: 5,
    policyRate: '84.38%',
    riskCount: 27,
    notRiskCount: 0,
    riskRate: '100.00%'
  },
  {
    num: 2,
    areaCode: '130200',
    area: '唐山ee市',
    normal: 32,
    closed: 0,
    stoped: 0,
    merger: 0,
    switched: 0,
    countAll: 32,
    assess: 32,
    notAssess: 0,
    assessRate: '100.00%',
    policy: 27,
    notPolicy: 5,
    policyRate: '84.38%',
    riskCount: 27,
    notRiskCount: 0,
    riskRate: '100.00%'
  }
];
